### ISSUE TITLE
Add attributes that describe dimension names?

### ISSUE THREAD

**Issue by LandonTClipp** [TerraFusion/advancedFusion#15]
I think it may be helpful to write attributes to the output datasets that describe what each dimension is. For instance, the MISR_Radiance dataset, when including all cameras and all bands, has dimensions:

9x4x23040x2092

Is there some documentation of exactly what the 1st and second dimensions are? I know first is camera, second is band, but *which* cameras and bands are they? Thoughts?

**Comment by jkimdevnc** [comment]
Hi Landon, For the answer, camera is the first and band is second for MISR.
We’ve discussed about adding it as attribute but didn’t have time to get to it.   I will add it to the user document.

For the input values,  you can refer to the MISR section of the https://github.com/TerraFusion/advancedFusion/blob/master/inputParameters_GenericExample.txt example input file.  (or inputParameters_MISR2MODIS.txt)

**Comment by LandonTClipp** [comment]
Thanks Jonathan. More specifically, my question is regarding the order of the first and second dimensions. 

Are the angles layed out like this:

AA = 0
AF = 1
AN = 2
BA = 3
BF = 4
...

And are the bands like this:

red = 0
green = 1
blue = 2
nir = 3

I just need to know this for the image verification scripts.

**Comment by jkimdevnc** [comment]
Landon, from the AFtool program point of view, it just takes in the order as user specified.

Not clear if we are talking the same thing.
You may want to ask Gunagyu about it, if it’s about a conceptual order.
I may recall these for camera, but not sure.
# MISR_CAMERA_ANGLE: any of < DF CF BF AF AN AA BA CA DA >
# MISR_RADIANCE: any of < Blue_Radiance Green_Radiance Red_Radiance NIR_Radiance >

**Comment by LandonTClipp** [comment]
Okay so when we are looking at a MISR_Radiance dataset that has these dimensions:

9x4x23040x2092

The first and second dimensions are simply ordered according to the order in which those parameters are given in the configuration file? For instance if I say,

MISR_CAMERA_ANGLE: DF CF BF AF AN AA BA CA DA 

then that means dset[0] (meaning selecting 0th index of first dimension) will give DF camera, dset[1] will give CF camera, etc. Is that correct?

**Comment by jkimdevnc** [comment]
Yes, correct.
