### ISSUE TITLE
ASTER Dimensions

### ISSUE THREAD

**Issue by LandonTClipp** [TerraFusion/advancedFusion#16]
Hi @jkimdevnc. Another quick question for you. Are users only allowed to specify one resolution for ASTER_RESOLUTION? If users wanted to specify multiple resolutions, would they need to do multiple runs of the AF tool? Also, I assume that the first dimension of the ASTER_Radiance represents the band, correct? Thanks.

**Comment by jkimdevnc** [comment]
Hi Landon,  yes, one ASTER_RESOLUTION is supported at a time currently, so it would require multiple runs for multiple resolutions. Correct, the first dimension of an ASTER output dataset represents the band.
